/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as RezerwacjaRouteImport } from './routes/rezerwacja'
import { Route as ZamowienieRouteImport } from './routes/zamowienie'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const RezerwacjaRoute = RezerwacjaRouteImport.update({
  id: '/rezerwacja',
  path: '/rezerwacja',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamowienieRoute = ZamowienieRouteImport.update({
  id: '/zamowienie',
  path: '/zamowienie',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/o-nas': typeof ONasRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/zamowienie': typeof ZamowienieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/o-nas': typeof ONasRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/zamowienie': typeof ZamowienieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/o-nas': typeof ONasRoute
  '/rezerwacja': typeof RezerwacjaRoute
  '/zamowienie': typeof ZamowienieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/kontakt' | '/menu' | '/o-nas' | '/rezerwacja' | '/zamowienie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/menu' | '/o-nas' | '/rezerwacja' | '/zamowienie'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/menu'
    | '/o-nas'
    | '/rezerwacja'
    | '/zamowienie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  MenuRoute: typeof MenuRoute
  ONasRoute: typeof ONasRoute
  RezerwacjaRoute: typeof RezerwacjaRoute
  ZamowienieRoute: typeof ZamowienieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezerwacja': {
      id: '/rezerwacja'
      path: '/rezerwacja'
      fullPath: '/rezerwacja'
      preLoaderRoute: typeof RezerwacjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamowienie': {
      id: '/zamowienie'
      path: '/zamowienie'
      fullPath: '/zamowienie'
      preLoaderRoute: typeof ZamowienieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  MenuRoute: MenuRoute,
  ONasRoute: ONasRoute,
  RezerwacjaRoute: RezerwacjaRoute,
  ZamowienieRoute: ZamowienieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
